### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ggomma** [devJaem/marketplace#1]
# feedback

## 총평

- 개발에 대한 이해도가 높습니다.
- 기능을 성공적으로 구현하였습니다.
- 코드가 읽기 좋고 깔끔합니다.
- readme.md 파일을 잘 작성하였습니다.

## 필요 구현 사항

1. 필수
- 상품 생성 API
  - [x] **상품명, 상품 설명, 담당자, 비밀번호**를 Request body(`req.body`)로 전달 받습니다.
  - [x] 상품은 두 가지 상태, **판매 중(`FOR_SALE`)및 판매 완료(`SOLD_OUT`)** 를 가질 수 있습니다.
  - [x] 상품 등록 시 기본 상태는 **판매 중(`FOR_SALE`)** 입니다.
  - [x] **생성 일시, 수정 일시**를 자동으로 생성합니다.
- 상품 목록 조회 API
  - [x] **상품 ID, 상품명, 상품 설명, 담당자, 상품 상태, 생성 일시, 수정 일시** 를 조회합니다.
  - [x] **비밀번호**를 포함하면 안됩니다.
  - [x] 상품 목록은 **생성 일시**를 기준으로 **내림차순(최신순)** 정렬합니다.
- 상품 상세 조회 API
  - [x] **상품 ID**를 Path Parameter(`req.params`)로 전달 받습니다.
  - [x] **상품 ID, 상품명, 상품 설명, 담당자, 상품 상태, 생성 일시, 수정 일시** 를 조회합니다.
  - [x] **비밀번호**를 포함하면 안됩니다.
- 상품 수정 API
  - [x] **상품 ID**를 Path Parameter(`req.params`)로 전달 받습니다.
  - [x] **상품명, 상품 설명, 담당자, 상품 상태, 비밀번호**를 Request body(`req.body`)로 전달 받습니다.
  - [x] **수정할 상품과 비밀번호 일치 여부를 확인**한 후, 동일할 때만 상품이 **수정**되어야 합니다. 일치하지 않을 경우, **“비밀번호가 일치하지 않습니다.”** 메세지를 반환합니다.
- 상품 삭제
  - [x] **상품 ID**를 Path Parameter(`req.params`)로 전달 받습니다.
  - [x] **비밀번호**를 Request body(`req.body`)로 전달 받습니다.
  - [x] **삭제할 상품과 비밀번호 일치 여부를 확인**한 후, 동일할 때만 글이 **삭제**되어야 합니다. 일치하지 않을 경우, **“비밀번호가 일치하지 않습니다.”** 메세지를 반환합니다.

2. 선택
- 에러 처리 (에러 처리 미들웨어)
  - [x] **상품 상세 조회, 수정, 삭제 시** **상품이 없는 경우**에는 “**상품이 존재하지 않습니다.**” 메세지를 반환합니다. **상품 목록 조회 시** **상품이 없는 경우**에는 **빈 배열(`[]`)을 반환**합니다.
  - [ ] **상품 생성 시** 입력 받은 상품명이 **기존에 등록 된 상품명과 동일한 경우**에는 **“이미 등록 된 상품입니다.”** 메세지를 반환합니다.
  - [x] **그 밖의 에러가 발생했을 때**에는 **“예상치 못한 에러가 발생했습니다. 관리자에게 문의해 주세요.”** 메세지를 반환합니다.
- 유효성 검증 (Joi)
  - [x] **상품 생성 시 정보가 빠진 경우**, **“OOO을(를) 입력해 주세요.”** 메시지를 반환합니다. 예) “상품명을 입력해 주세요”, “담당자를 입력해 주세요.” 등…
  - [x] **상품 수정, 삭제 시 비밀번호가 없는 경우**, **“비밀번호를 입력해 주세요.”** 메세지를 반환합니다.
  - [x] **상품 수정 시** 상품 상태에 `FOR_SALE`, `SOLD_OUT` 이 외의 다른 값이 입력된 경우, **“상품 상태는 [FOR_SALE,SOLD_OUT] 중 하나여야 합니다.”** 메세지를 반환합니다.

### 코드는 기능별로 나누는 것이 좋습니다.
joi에 관련된 내용은 별도 파일로 작성하는 것이 가독성에 좋습니다.

https://github.com/devJaem/marketplace/blob/99269395ba6c6b519843843fc471d5fca1523e73/src/routes/products.router.js#L8-L52

### `Put` vs `Patch`
데이터의 일부만 수정할 경우 `Put` 보다는 `Patch`를 사용하는 것이 좋습니다.

https://github.com/devJaem/marketplace/blob/99269395ba6c6b519843843fc471d5fca1523e73/src/routes/products.router.js#L153

### 중복 코드는 별도 함수로
중복으로 사용하는 코드가 있다면 이를 별도의 함수로 만들어주는 것이 사용성에 도움이 됩니다.

https://github.com/devJaem/marketplace/blob/99269395ba6c6b519843843fc471d5fca1523e73/src/routes/products.router.js#L160-L164

### 오탈자
아래의 경우 오타가 있습니다.

https://github.com/devJaem/marketplace/blob/99269395ba6c6b519843843fc471d5fca1523e73/src/routes/products.router.js#L93

**Comment by devJaem** [comment]
수정 완료했습니다. 감사합니다.
